from collections.abc import Sequence
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from app.domain.audit import AgentAction, ToolExecution
from app.domain.enums import RescueStatus
from app.domain.events import Event, EventOutcome
from app.domain.rescue import Rescue


class RescueRepository(Protocol):
    async def get(self, rescue_id: UUID) -> Rescue | None: ...

    async def create(self, rescue: Rescue, *, donor_organization_id: UUID) -> Rescue: ...

    async def save(self, rescue: Rescue) -> Rescue: ...

    async def transition(self, rescue: Rescue, target: RescueStatus) -> Rescue: ...

    async def lock_for_update(self, rescue_id: UUID) -> Rescue | None: ...


class OrganizationRepository(Protocol):
    async def exists(self, organization_id: UUID) -> bool: ...


class EventRepository(Protocol):
    async def get_by_idempotency_key(self, key: str) -> Event | None: ...

    async def append(self, event: Event) -> Event: ...

    async def list_for_rescue(self, rescue_id: UUID) -> Sequence[Event]: ...

    async def set_outcome(self, event_id: UUID, outcome: EventOutcome) -> None: ...

    async def get_outcome(self, event_id: UUID) -> EventOutcome | None: ...


class AgentActionRepository(Protocol):
    async def append(self, action: AgentAction) -> AgentAction: ...

    async def list_for_rescue(self, rescue_id: UUID) -> Sequence[AgentAction]: ...


class ToolExecutionRepository(Protocol):
    async def append(self, execution: ToolExecution) -> ToolExecution: ...

    async def list_for_action(self, action_id: UUID) -> Sequence[ToolExecution]: ...

    async def list_for_rescue(self, rescue_id: UUID) -> Sequence[ToolExecution]: ...


class UnitOfWork(Protocol):
    @property
    def organizations(self) -> OrganizationRepository: ...

    @property
    def rescues(self) -> RescueRepository: ...

    @property
    def events(self) -> EventRepository: ...

    @property
    def agent_actions(self) -> AgentActionRepository: ...

    @property
    def tool_executions(self) -> ToolExecutionRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def flush(self) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
